redclock:
  # This option remove  pulsing red stone circuit automatic
  # The value is how many change count in one second
  use: true
  value: 25

restart:
  # This option restart your server automatic
  # It act after {value} hours
  # It stop your server if online less then {limit}
  # WARN: Need a loop script to function
  # if you need not a loop script please disable it
  use: true
  value: 24
  limit: 0
  
spawnmob:
  # This option protect mob farm lag your server
  # {value} same mobs allowed to spawn in a range
  # Please don't modify it if not necessary
  use: true
  value: 16
  
joinbot:
  # This option protect joinbot crash your server
  # It allow 30 player login in {value} second
  # It allow a same IP login one time in {value} second
  # Please don't modify it if not necessary
  use: true
  value: 60
  
saveworld:
  # This option save your world data every {value} second
  # Disable "AutoSave" and "AutoSaveWorld" automatic
  # This value must be greater than 0
  # Please don't modify it if not necessary
  use: true
  value: 60
  
keepfarm:
  # This option protect your farm from jumper
  use: true
  
explosion:
  # This option prevent remove block from a explosion
  use:true
  
spigot:
  # This option modify your spigot.yml if exist
  # Modify entity-activation-range to get performance
  # This value must be greater than 0 
  # Lower get better performance
  # Please don't modify it if not necessary
  use: true
  value: 4

version: 0.2.3