name: ${project.name}
version: ${project.version}
main: com.mengcraft.server.Protect
commands:
  protect:
    description: Admin command for this.
    permission: server.admin
permissions:
  server.admin:
     description: Admin permission for this.
     default: op