name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
commands:
  protect:
    description: Admin command for this.
    permission: server.admin
permissions:
  server.admin:
     description: Admin permission for this.
     default: op